### ISSUE TITLE
Doesn't work with Unity 2018.3  or MessagePack 1.7.3.5 (?)

### ISSUE THREAD

**Issue by angusmf** [Cysharp/MasterMemory#9]
Using Unity 2018.3.7.  Importing MasterMemory as-is results in 58 different "type or namespace cannot be found" errors for the following: TypeBuilder, ModuleBuilder, AssemblyBuilder, LocalBuilder, FieldBuilder, MethodBuilder and ILGenerator. 

When I delete the MessagePack folder and import the MessagePack 1.7.3.5, all those errors go away and a new one appears:

`Assets\Plugins\MasterMemory\Scripts\Loader.cs(57,13): error CS0103: The name 'DefaultResolver' does not exist in the current context
`
